build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.16
releases:
  latest:
    candidate:
      architecture: amd64
      product: ocp
      stream: nightly
      version: "4.8"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: unit
  commands: make test
  container:
    from: src
- as: templates
  commands: make test-templates
  container:
    from: src
- as: integration
  commands: make test-integration
  container:
    from: src
- as: e2e
  steps:
    cluster_profile: aws
    test:
    - as: e2e
      commands: ./openshift/release/e2e-tests.sh
      from: src
      resources:
        requests:
          cpu: 100m
    workflow: ipi-aws
zz_generated_metadata:
  branch: release-next
  org: openshift-knative
  repo: kn-plugin-func
