build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.19
promotion:
  name: "4.14"
  namespace: ocp
releases:
  initial:
    integration:
      name: "4.14"
      namespace: ocp
  latest:
    integration:
      include_built_images: true
      name: "4.14"
      namespace: ocp
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: unit
  commands: git log -n 2 --pretty=format:"%H %s" && make test
  container:
    from: src
- as: e2e
  steps:
    cluster_profile: aws
    test:
    - as: e2e
      commands: make e2e
      from: src
      resources:
        requests:
          cpu: 100m
    workflow: ipi-aws
zz_generated_metadata:
  branch: release-next
  org: securesign
  repo: rekor
